### ISSUE TITLE
如何用更新tools

### ISSUE THREAD

**Issue by hierarch41** [2013fangwentao/Multi_Sensor_Fusion#12]
你好，我是新手，请问一下如何用更新tools呀？我对submodules不会用

**Comment by 2013fangwentao** [comment]
你这边按照submodules更新出现了什么问题？我在文档里面写的过程你这边更新不了么？

**Comment by 2013fangwentao** [comment]
> 你好，我是新手，请问一下如何用更新tools呀？我对submodules不会用

你这边按照submodules更新出现了什么问题？我在文档里面写的过程你这边更新不了么？

**Comment by hierarch41** [comment]
当我更新时出现问题：
:~$ git checkout -b dev origin/dev
fatal: Cannot update paths and switch to branch 'dev' at the same time.
Did you intend to checkout 'origin/dev' which can not be resolved as commit?

**Comment by 2013fangwentao** [comment]
> 当我更新时出现问题：
> :~$ git checkout -b dev origin/dev
> fatal: Cannot update paths and switch to branch 'dev' at the same time.
> Did you intend to checkout 'origin/dev' which can not be resolved as commit?

你应该在dev版本上了，直接执行下面的两个命令试试

**Comment by hierarch41** [comment]
我执行完了，但是tools并没有更新。
:~$ git checkout -b dev origin/dev
fatal: Cannot update paths and switch to branch 'dev' at the same time.
Did you intend to checkout 'origin/dev' which can not be resolved as commit?
:~$ git submodule init
:~$ git submodule update
:~$

**Comment by 2013fangwentao** [comment]
确定进到对应的文件夹下面么？

**Comment by hierarch41** [comment]
哦哦，可以了。非常感谢
