### ISSUE TITLE
关于相机姿态表示的问题

### ISSUE THREAD

**Issue by Hchu2** [2013fangwentao/Multi_Sensor_Fusion#17]
您好，您分享的代码非常具有学习的价值。之前有幸和您做过类似的工作，所以有一个疑问希望您解答一下。我有发现您惯导所采用的机械编排是n系，在相机扩维的时候，所得到的相机姿态为R_c_n，当你在做量测更新的时候，涉及到R_c0_n  R_c1_n ~~~R_ck_n这些相机状态量，此时这些相机姿态的上标n已经不再是同一个n，东北天的指向随着运动发生了变化，也就是这些状态量并非表示在同一参考坐标系下，虽然可能在短时间的载体运动不会造成太大的干扰，但我认为这样不是特别的严谨，而把相机姿态扩维在e系下会更好一些。

**Comment by 2013fangwentao** [comment]
你好，我采用的是e系编排的，您看navmech.cc中我所做的编排代码是在e系进行的，在NavInfo的结构体中，att的量是n系的姿态，其他姿态表达方式都是在e系的
非常感谢您的关注，希望多交流！

**Comment by Hchu2** [comment]
哦哦 ，是我阅读的不够仔细 抱歉。另外还有一个小问题想和你交流一下，你是否觉得PPP/IMU/VISION的三者紧组合有它的意义呢，现在已经有RTK+IMU+单目VISION的三者紧组合的论文出现了，并且证明了确有提升

**Comment by 2013fangwentao** [comment]
我认为在复杂环境是有意义的，但是对于相对开阔的条件可能效果不会有多突出，RTK本身定位精度是高于PPP，三者的融合都可以带来提升，PPP肯定也可以的，重点是试验场景上的选取

**Comment by Hchu2** [comment]
十分感谢你的回答
