### ISSUE TITLE
GPS coordinate using to fusion

### ISSUE THREAD

**Issue by nguyentuanHUST** [2013fangwentao/Multi_Sensor_Fusion#19]
Hi. I'm interesting in your project. I have a question about GPS data.
What type of coordinate are GPS data measurement? I guess it's ENU but there is not available dataset using or proper paper.
Does it need to convert GPS measurement to proper frame before using to update Kalman Filter?

**Comment by ChunqiDai** [comment]
The GPS positioning result is obtained by PPP/INS tightly coupled integration and is expressed by  XYZ in ECEF(Earth-Centered, Earth-Fixed). ENU  can easily be transferred to XYZ in ECEF.

**Comment by nguyentuanHUST** [comment]
Isn't it obtained by GPS devices? 
I see the standard covariance is expressed in ENU coordinate, isn't it?
Can I calculate GPS velocity by GPS position and different time by formula v = delta_x / delta_t ? My GPS device does not report velocity.

**Comment by ChunqiDai** [comment]
The raw measurement data is obtained by a GNSS receiver. We use PPP(Precise Point Positioning)/INS tightly coupled integrated algorithm to resolve ,then get the positioning result  in ECEF frame. INS/IMU data processing is also in ECEF frame.While  evaluating the  accuracy of positioning, we transfer the result to navigation frame(NED) for convenience. We focus on positioning result in this program and velocity is obtained by IMU. I can't guess why you need GPS velocity. Generally when we need to analyse the velocity, we obtain the GPS velocity by Doppler Measurements rather than use position and time, which is not accurate enough.

**Comment by nguyentuanHUST** [comment]
As I understand, there is a rotation matrix between original IMU  frame and ECEF frame.  It would be pre-process to calculate that rotation matrix, isn't it?

**Comment by ChunqiDai** [comment]
We didn't pre-process to transfer the IMU raw data from IMU frame to ECEF frame. Actually,we just implement the mechanization algorithm in ECEF frame rather than navigation frame.

**Comment by nguyentuanHUST** [comment]
I don't have mechanization algorithm in ECEF frame to get INS/IMU data processing in ECEF frame currently. 
Can you suggest me to run this project correctly if our configurations have GPS devices with output geographic location given latitude longitude and altitude, IMU devices with outputs acc and rate angle in body frame.
My assumtion is: 
Upon receiving geographic location, convert to ECEF frame then pass to data queue.
Upon receiving IMU outputs acc and rate angle, convert to ECEF frame some how then pass to data queue.
The same process with camera data.
We are using ROS to communicate between devices

**Comment by ChunqiDai** [comment]
Our program can deal with IMU raw data. There is mechanization algorithm inside the program. The IMU data we used is arranged  in our own format. You can see the tools in our program. There is a tool named RawImutoImuData, by which we can get the data format we want. Camera data is also processed inside our program and you need't pre-process them.So,you only need transfer your GPS data to ECEF frame XYZ. There is still something to be improved and  we will give more tips later.

**Comment by nguyentuanHUST** [comment]
Thanks a lot for all the answers
