### ISSUE TITLE
一些疑问和探讨

### ISSUE THREAD

**Issue by ouyangandy** [2013fangwentao/Multi_Sensor_Fusion#2]
博主，你真的是太厉害了，目前我正研究mvo+IMU+gps的一个组合定位，虽然已经毕业工作了，但这个方向是刚开始学习，有很多问题想跟你请教。你觉得mvo+imu+gps，完全基于松耦合能做吗？我看一些方法是基于vio+gps做的比如VINS-fusion的双目+gps，单目视觉里程计这块我也刚开始研究没多久。
ps：我在 `nvinitialized.cc`中加入了头文件`#include <numeric>`，才能编译成功，这是`std::accumulate`需要的头文件。博主，我加您qq去啦，有疑问的时候希望能跟您请教。

**Comment by 2013fangwentao** [comment]
你好，我也是刚刚开始做，目前我这边想先基于松耦合做一套能够运行的程序，视觉方面想以msckf的形式和IMU GPS组合起来。VINS-fusion我还没有看过，暂时还在做GPS+IMU部分，后续视觉方面想参考VINS的部分再做，有兴趣我们可以一起交流学习！

**Comment by 2013fangwentao** [comment]
> 博主，你真的是太厉害了，目前我正研究mvo+IMU+gps的一个组合定位，虽然已经毕业工作了，但这个方向是刚开始学习，有很多问题想跟你请教。你觉得mvo+imu+gps，完全基于松耦合能做吗？我看一些方法是基于vio+gps做的比如VINS-fusion的双目+gps，单目视觉里程计这块我也刚开始研究没多久。
> ps：我在 `nvinitialized.cc`中加入了头文件`#include <numeric>`，才能编译成功，这是`std::accumulate`需要的头文件。博主，我加您qq去啦，有疑问的时候希望能跟您请教。

你好，我也是刚刚开始做，目前我这边想先基于松耦合做一套能够运行的程序，视觉方面想以msckf的形式和IMU GPS组合起来。VINS-fusion我还没有看过，暂时还在做GPS+IMU部分，后续视觉方面想参考VINS的部分再做，有兴趣我们可以一起交流学习！
