### ISSUE TITLE
The picture in README.md is invalid

### ISSUE THREAD

**Issue by wangyazhao001** [2013fangwentao/Multi_Sensor_Fusion#22]
Hi! I am also learning the navigation direction. I saw your project, so I want to study it, but the picture in your README.md is invalid. Can I fix it if have time?

**Comment by 2013fangwentao** [comment]
感谢你的关注，图片无效可能是你那边网络的原因，改一下host应该就可以了，另外就是readme的图片都在文件夹 pic目录，你可以clone下来，查看。
