### ISSUE TITLE
有一些关于项目的小疑问

### ISSUE THREAD

**Issue by hmf21** [2013fangwentao/Multi_Sensor_Fusion#23]
博主您好，这个项目十分清楚和完整，我也十分想学习学习您的工作，想有几点关于项目的疑问，请麻烦您拨冗解答下：
1、当前我看实现的是GNSS+IMU的紧耦合？想请问博主有开展VIO+GNSS的实验研究吗？
2、关于耦合GNSS数据的定位方式可能我不是很懂，想请问下GNSS+IMU的耦合中使用GPS数据是只需要经纬高数据吗？还是需要更基本的例如伪距等其他的数据呢？

**Comment by 2013fangwentao** [comment]
非常感谢你的关注。
1.基于团队成果，我这边做了GNSS 的PPP技术与IMU紧组合，在原始观测值层面的，但是这部分代码没有开源，主要是涉及了其他老师和同学的成果，望理解。开源的这部分代码，也就是这个库，是VIO+GNSS的部分，GNSS参与主要体现在前面PPP+IMU紧组合输出的位置信息（ECEF系的XYZ）
2.在做GNSS+IMU的时，使用的是原始观测数据，伪距+相位+多普勒观测值，但是在这部分代码中则是仅仅使用紧组合输出的位置信息，两部分是一种级联滤波的策略
希望可以解答你的疑问，再次感谢你的关注

**Comment by hmf21** [comment]
感谢您能够抽空回复，您开源的这部分工作对我而言也有非常多可学习的地方，您回复中指的意思是不是可以理解为您这里完成的是级联滤波框架下的VIO+GNSS(仅XYZ数据)工作呢~
再次感谢！

**Comment by 2013fangwentao** [comment]
是的，这部分内容是VIO+GNSS位置数据的融合

**Comment by hmf21** [comment]
好的，再次感谢您的回复~
