### ISSUE TITLE
请问glog 和 eigen 的版本号具体是多少呢

### ISSUE THREAD

**Issue by hubgeter** [2013fangwentao/Multi_Sensor_Fusion#27]

**Comment by coolcl** [comment]
邮件已收到，我会尽快回复，谢谢！

**Comment by 2013fangwentao** [comment]
不好意思，这个很久之前了，已经不记得了。看下最新的能不能编译过，如果什么问题对应改一下应该就好了

**Comment by hubgeter** [comment]
好的 感谢您的回复。另外我想询问一下，您机器内存是多大的呢，我每次运行都会抛出std::bad_alloc()异常，我怀疑是内存不足导致的。

**Comment by coolcl** [comment]
邮件已收到，我会尽快回复，谢谢！

**Comment by HariwW** [comment]
你好，你成功运行了代码了吗，能否告诉我你运行的glog和Eigen的版本号。

我在运行代码时，会报出Aborted (core dumped)的错误，可能是filter_->TimeUpdate(PHI, Q, base_data->get_time());这段代码出了问题

**Comment by coolcl** [comment]
邮件已收到，我会尽快回复，谢谢！
