### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Maxgukr** [2013fangwentao/Multi_Sensor_Fusion#4]
在和SLAM做组合的时候，有文章说用IEKF(invarient extended kf)的效果比EKF好，大神了解IEKF吗?

**Comment by 2013fangwentao** [comment]
> 在和SLAM做组合的时候，有文章说用IEKF(invarient extended kf)的效果比EKF好，大神了解IEKF吗?

大佬说笑了，你才是大神。我现在做的这些都是偏向于传统的方法，IEKF还没有了解过，具体是对滤波器哪个方面做了改进呢？我现在了解的是MSCKF多状态约束滤波或者优化一些方式来做。
